---

## This file contains configuration for the access application, depending on the preferences of the user.

default: &default
  available_locales: # first locale is the default one
    - en
    - el
  default_phone_country: en
  email:
    default_from: no-reply@access.hellasgrid.gr
  snapshot_limit: 20
  registration:
    accept_only_institutional_mails: "false"
  CA:
    crl_distribution_point: http://crl.grid.auth.gr/hellasgrid-ca-2006/82b36fca.crl
    ocsp_endpoint: ""
    key_usages:
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
    extended_key_usages:
      - clientAuth
      - emailProtection
    policy_id: "1.3.6.1.4.1.16515.20.1.1.2.3"
    cps_uris:
      - http://crl.grid.auth.gr/hellasgrid-ca-2006/cps/HellasGrid-CA-CP-CPS.pdf
    user_notice:
      explicit_text: ""
      organization: ""
      notice_numbers: ""


###### E-mail ######
development:
  <<: *default

production:
  <<: *default

test:
  <<: *default