---

- name: Checkout code from git
  git: repo={{ git_application_url }}
       dest={{ application_path }}
       update=yes
       version={{ application_branch }}
  notify: restart apache
  tags: install_access

# To be introduced in Ansible 2.0 (alpha version on September 2015)
# - name: Bundle install
#   bundler: state=present deployment=yes chdir={{ application_path }}/access/Gemfile

- name: Bundle install
  shell: bash -lc "bundle install" chdir="{{ application_path }}/access"
  become: yes
  become_user: "{{ application_user }}"
  notify: restart apache
  tags:
    - install_access
    - install_gems

- name: restart apache
  service: name=httpd state=restarted enabled=yes

- name: Copy secrets.yml
  template: src=config/secrets.yml.j2 dest={{ application_path }}/access/config/secrets.yml
            owner={{ application_user }} group={{ application_user }} mode=0644
  notify: restart apache
  tags: install_access

- name: Copy database.yml
  template: src=config/database.yml.j2 dest={{ application_path }}/access/config/database.yml
            owner={{ application_user }} group={{ application_user }} mode=0640
  notify: restart apache
  tags: install_access

##########################################################
############ Change owner of the application  ############
##########################################################

- name: Change owner of config.ru (otherwise it will run as apache user)
  file: path={{ application_path }}/access/config.ru owner={{ application_user }}
        group={{ application_user }}
  notify: restart apache
  tags: install_access

- name: restart apache
  service: name=httpd state=restarted enabled=yes

##########################################################
########### Create necessary rails directories ###########
##########################################################
- name: Create folders tmp, cache
  file: path={{ application_path }}access/tmp/cache state=directory owner={{ application_user }}
        group={{ application_user }}
  tags:
    - create_rails_directories

- name: Create folder log
  file: path={{ application_path }}access/log state=directory owner={{ application_user }}
        group={{ application_user }}
  tags:
    - create_rails_directories

- name: Create file {production,development,test}.log
  file: path={{ application_path }}access/log/{{ item }}.log state=touch owner={{ application_user }}
        group={{ application_user }}
  with_items:
    - production
    - development
    - test
  tags:
    - create_rails_directories


#####################################
########### Rake db tasks ###########
#####################################
- name: rake db:migrate
  shell: bash -lc "rake db:schema:load" chdir="{{ application_path }}/access"
  tags:
    - rake_db_tasks

##########################################################
###### Change owner of certain directories/files  ########
##########################################################

- name: Change owner of db folder
  file: path={{ application_path }}/access/db owner={{ application_user }}
        group={{ application_user }}
  notify: restart apache
  tags: install_access

- name: Change owner of database
  file: path={{ application_path }}/access/db/development.sqlite3 owner={{ application_user }}
        group={{ application_user }}
  notify: restart apache
  tags: install_access

- name: restart apache
  service: name=httpd state=restarted enabled=yes

# This task is to be run once. If the data have already been seeded and the seed
# file has changed, the process of updating has to be done manually.
# - name: rake db:seed
#   shell: bash -lc "rake db:seed" chdir="{{ application_path }}/access"
#   tags:
#     - rake_db_tasks
